OrganizerApp.WebUI/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Collections.Specialized;
using OrganizerApp.BllDtos.Projects;
using OrganizerApp.DataCirculationHelpers;
using RestSharp;
using System.Threading.Tasks;
using OrganizerApp.WebUI.Helpers.Api.OrganizerApp.Projects;

namespace OrganizerApp.WebUI.Controllers
{
    public class NavigationController : Controller
    {
        private IOrganizerAppProjectApiRequestHandler _apiRequestHandler;


        public NavigationController(IOrganizerAppProjectApiRequestHandler apiRequestHandler)
        {
            _apiRequestHandler = apiRequestHandler;
        }


        public PartialViewResult Index()
        {
            var getProjectsTask = Task.Run(() => _apiRequestHandler.GetProjectsHeaders(projectsType: ProjectType.Active));
            IEnumerable<ProjectBase> viewModel = new List<ProjectBase>();
            viewModel = getProjectsTask.GetAwaiter().GetResult();

            return PartialView(viewModel);
        }
    }
}
 

OrganizerApp.WebUI/Controllers/ProjectsController.cs
using OrganizerApp.WebUI.Models;
using OrganizerApp.BllDtos.Projects;
using OrganizerApp.WebUI.Infrastructure.Validation;
using FluentValidation.Results;
using OrganizerApp.WebUI.Helpers.View.ContentGenerator.Implementations;
using OrganizerApp.DataCirculationHelpers;
using System.Web.Mvc;
using System.Threading.Tasks;
using OrganizerApp.WebUI.Helpers.Api.OrganizerApp.Projects;

namespace OrganizerApp.WebUI.Controllers
{
    public class ProjectsController : Controller
    {
        private IOrganizerAppProjectApiRequestHandler _apiRequestHandler;


        public ProjectsController(IOrganizerAppProjectApiRequestHandler apiRequestHandler)
        {
            _apiRequestHandler = apiRequestHandler;
        }


        [HttpGet]
        public async Task<ActionResult> List(string searchPhrase, ProjectType projectsType = ProjectType.All)
        {
            var getProjectsTask = _apiRequestHandler.GetProjectsHeadersWithPriorityAndState(searchPhrase, projectsType);
            ProjectsListViewModel viewModel = new ProjectsListViewModel();
            viewModel.Projects = await getProjectsTask;

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ProjectEditViewModel viewModel = new ProjectEditViewModel()
            {
                Project = new ProjectDetail { ID = 0 },
                ContentGenerator = new ProjectEditContentGenerator()
            };
            return View("Edit", viewModel);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var getProjectTask = _apiRequestHandler.GetProjectById(id);
            ProjectEditViewModel viewModel = new ProjectEditViewModel();
            viewModel.Project = await getProjectTask;

            return View(viewModel);
        }



        [HttpPost]
        public async Task<ActionResult> Edit(ProjectDetail project)
        {
            ProjectDetailValidator validator = new ProjectDetailValidator();
            ValidationResult validationResults = validator.Validate(project);

            if(!validationResults.IsValid)
            {
                ProjectEditViewModel viewModel = new ProjectEditViewModel()
                {
                    Project = project,
                };

                foreach (var error in validationResults.Errors)
                {
                    ModelState.AddModelError(nameof(ProjectEditViewModel.Project) + '.' + error.PropertyName, error.ErrorMessage);
                }

                return View(viewModel);
            }

            await _apiRequestHandler.SaveProject(project);
            return RedirectToAction("List");
        }

        
        public async Task<ActionResult> Search(string searchPhrase)
        {
            var searchProjectsTask = _apiRequestHandler.SearchProjects(searchPhrase);
            ProjectsListViewModel viewModel = new ProjectsListViewModel();
            viewModel.Projects = await searchProjectsTask;

            return View("List" , viewModel);
        }
    }
}

OrganizerApp.WebUI/Controllers/TasksController.cs
using System;
using OrganizerApp.WebUI.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Collections.Specialized;
using System.Web;
using Newtonsoft.Json;
using OrganizerApp.BllDtos.Tasks;
using OrganizerApp.BllDtos.Projects;
using FluentValidation.Results;
using OrganizerApp.WebUI.Infrastructure.Validation;
using OrganizerApp.WebUI.Helpers.View.ContentGenerator.Implementations;
using OrganizerApp.DataCirculationHelpers;
using OrganizerApp.WebUI.Helpers.Api.OrganizerApp.Tasks;
using OrganizerApp.WebUI.Helpers.Api.OrganizerApp.Projects;

namespace OrganizerApp.WebUI.Controllers
{
    public class TasksController : Controller
    {
        private IOrganizerAppTaskApiRequestHandler _taskApiRequestHandler;
        private IOrganizerAppProjectApiRequestHandler _projectApiRequestHandler;


        public TasksController(IOrganizerAppTaskApiRequestHandler apiRequestHandler , IOrganizerAppProjectApiRequestHandler projectApiRequestHandler)
        {
            _taskApiRequestHandler = apiRequestHandler;
            _projectApiRequestHandler = projectApiRequestHandler;
        }


        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> List(string timeType , int? projectID , string searchPhrase , string date , TaskType tasksType = TaskType.All)
        {
            var getTasksTask = _taskApiRequestHandler.GetTasksHeadersWithPriority(timeType , projectID , searchPhrase , date , tasksType);
            TasksListViewModel viewModel = new TasksListViewModel();
            viewModel.Tasks = await getTasksTask;

            return View(viewModel);
        }

        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Create()
        {
            var getProjectsTask = _projectApiRequestHandler.GetProjectsHeaders(projectsType: ProjectType.Active);
            TaskEditViewModel viewModel = new TaskEditViewModel()
            {
                Task = new TaskDetail { ID = 0 }
            };
            viewModel.ActiveProjects = await getProjectsTask;

            return View("Edit", viewModel);
        }

        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Edit (int id)
        {
            var getProjectsTask = _projectApiRequestHandler.GetProjectsHeaders(projectsType: ProjectType.Active);
            var getTaskTask = _taskApiRequestHandler.GetTaskById(id);

            TaskEditViewModel viewModel = new TaskEditViewModel();
            viewModel.ActiveProjects = await getProjectsTask;
            viewModel.Task = await getTaskTask;

            return View(viewModel);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Edit(TaskDetail task)
        {

            TaskDetailValidator validator = new TaskDetailValidator();
            ValidationResult validationResults = validator.Validate(task);

            if (!validationResults.IsValid)
            {
                var getProjectsTask = _projectApiRequestHandler.GetProjectsHeaders(projectsType: ProjectType.Active);

                foreach (var error in validationResults.Errors)
                {
                    ModelState.AddModelError(nameof(TaskEditViewModel.Task) + '.' + error.PropertyName, error.ErrorMessage);
                }

                TaskEditViewModel viewModel = new TaskEditViewModel()
                {
                    Task = task,
                };
                viewModel.ActiveProjects = await getProjectsTask;
                
                return View(viewModel);
            }

            await _taskApiRequestHandler.SaveTask(task);

            return RedirectToAction("List");
        }


        public async System.Threading.Tasks.Task<ActionResult> Search(string searchPhrase)
        {
            var searchTasksTask = _taskApiRequestHandler.SearchTasks(searchPhrase);
            TasksListViewModel viewModel = new TasksListViewModel();
            viewModel.Tasks = await searchTasksTask;

            return View("List", viewModel);
        }
    }
}

OrganizerApp.WebUI/Views/Shared/_ExtendedProjectView.cshtml
@model OrganizerApp.BllDtos.Projects.ProjectBaseWithPriorityAndState


<div id="@Model.ID" class="extendedView textDecorationOff projectItem @( (Model.State == "done") ? "done" : "" )">
    <div class="details">
        <input type="hidden" name="id" value="@Model.ID" />
        <input class="projectDoneCheckbox" type="checkbox" @( (Model.State == "done") ? "checked disabled" : "" ) />

        <div class="priority @Html.GetPriorityCssClassName(Model.Priority)">
            &nbsp;
        </div>
        @Html.ActionLink(Model.Name , "Edit" , "Projects" , new { id = Model.ID } , new { id = "projectItemLink" })
    </div>
</div>

OrganizerApp.WebUI/Views/Shared/_ExtendedTaskView.cshtml
@model OrganizerApp.BllDtos.Tasks.TaskBaseWithPriority


    <div id="@Model.ID" class="extendedView textDecorationOff taskItem">
        <div class="details">
            <input type="hidden" name="id" value="@Model.ID" />
            <input class="taskDoneCheckbox" type="checkbox" />

            <div class="priority @Html.GetPriorityCssClassName(Model.Priority)">
                &nbsp;
            </div>
            @Html.ActionLink(Model.Name, "Edit", "Tasks", new { id = Model.ID }, null)
        </div>
    </div>

OrganizerApp.WebUI/Views/Shared/_Layout.cshtml
@using OrganizerApp.WebUI.Infrastructure.Resources.Languages

<!DOCTYPE html>
<html lang="pl-PL">
    <head>
        <meta charset="utf-8">
        <title> OrganizerApp </title>
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Site.css")">
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap-iso.css")">
        @*<link rel="java" type="text/css" href="@Url.Content("~/Content/bootstrap-iso.css")">*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="text/javascript" src="@Url.Content("~/MyScripts/LayoutScripts.js")"></script>
    </head>
    <body>
            <div id="container">
                <header>
                    <div class="inlineFlex">
                        <div class="bootstrap-iso">
                            <div class="createButtonsWrapper">
                                @Html.ActionLink(LocalizedText.CreateProject , "Create", "Projects", null, new { @class = "btn btn-default" })
                                @Html.ActionLink(LocalizedText.CreateTask , "Create", "Tasks", null, new { @class = "btn btn-default" })
                            </div>
                        </div>
                            <div class="searchFormWrapper inline">
                                <form id="searchForm" method="get">
                                    <input id="searchPhraseText" type="search" name="searchPhrase" placeholder="@LocalizedText.SearchByPhrase" />
                                    <label> <input name="searchType" type="radio" value="@Url.Action("Search" , "Projects")" checked /> @LocalizedText.ProjectsSearch </label>
                                    <label> <input name="searchType" type="radio" value="@Url.Action("Search" , "Tasks")" /> @LocalizedText.TasksSearch </label>
                                    <input type="submit" name="x" value="@LocalizedText.Search" formmethod="post"/>
                                </form>
                            </div>
                    </div>
                </header>
                <div id="content">
                    <aside>
                        @Html.Action("Index", "Navigation");
                    </aside>
                    <main>
                        <div id="items">
                            @RenderBody()
                        </div>
                    </main>
                </div>
                <footer>
                    <p> OrganizerApp 2017 </p>
                </footer>
            </div>
            @RenderSection("scripts", false)
    </body>  
</html>

OrganizerApp.WebUI/Views/Shared/_SimpleProjectView.cshtml
@model OrganizerApp.BllDtos.Projects.ProjectBase


<li> @Html.ActionLink(Model.Name, "Edit", "Projects", new { Model.ID }, new { @class = "label label-default" }) </li>